name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
    paths: [ 'frontend/**' ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and Build
        working-directory: ./frontend
        run: |
          npm install
          npm run build -- --configuration=production

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # Note the added /browser at the end
          folder: frontend/dist/frontend/browser
          branch: gh-pages